swagger: "2.0"
info:
  description: "API с использование Python Flask"
  version: "1.0.0"
  title: "Занятие 13. Development Backend"
host: "127.0.0.1:5000"
basePath: "/api"
tags:
- name: "post"
  description: "Access to Petstore orders"
schemes:
- "http"
paths:
  /post:
    get:
      tags:
      - "post"
      summary: "Get all posts"
      description: ""
      operationId: "get"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: object
            properties:
              lenght:
                type: integer
              posts:
                type: "array"
                items:
                  $ref: "#/definitions/Post"
    post:
      tags:
      - "post"
      summary: "Add a new post"
      description: ""
      operationId: "post"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "title"
        in: "formData"
        description: "Title of post"
        required: true
        type: "string"
      - name: "description"
        in: "formData"
        description: "Description of post"
        required: true
        type: "string"
      responses:
        "201":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: "bad request"
          schema:
            $ref: "#/definitions/ApiResponse"
definitions:
  Post:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      description:
        type: "string"
      created_on:
        type: "array"
        items:
          type: "string"
        minItems: 2
      updated_on:
        type: "array"
        items:
          type: "string"
        minItems: 2
    required:
      - id
      - title
      - description
  ApiResponse:
    type: "object"
    properties:
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"